apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlops-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Shivaji1487/mlops-gitospv2.git'
    targetRevision: HEAD
    path: chart/ml-service
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true