apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlops-app-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/Shivaji1487/mlops-gitops.git'
    targetRevision: HEAD
    path: 'charts/ml-service'
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true